'use strict';
const indexHome=publicHome;
publicHome=function(){let html=indexHome();html=html.replace(/<section class="client-note">[\s\S]*$/,'');html=html.replace('What would you like<br>to move forward?','Good advice starts<br>with a conversation.').replace('என்ன உதவி<br>தேவைப்படுகிறது?','உங்கள் தேவையைப்<br>பற்றிப் பேசலாம்.');return html+`
<section class="first-meeting"><div class="meeting-title"><h2>${tr('You don’t need to<br>have it all figured out.','எல்லாவற்றையும் அறிந்திருக்க<br>வேண்டிய அவசியமில்லை.')}</h2><p>${tr('A first conversation is simply a place to begin.','எங்கிருந்து தொடங்குவது என்று தெரியவில்லையா? முதலில் உங்கள் சூழ்நிலையைப் பற்றிப் பேசலாம்.')}</p></div><ol class="meeting-steps"><li><h3>${tr('Tell us what is happening','என்ன நடந்துள்ளது என்பதைச் சொல்லுங்கள்')}</h3><p>${tr('Explain the situation in your own words. Tamil or English—whichever feels comfortable.','சட்டச் சொற்களை அறிந்திருக்க வேண்டியதில்லை. உங்களுக்கு வசதியாகத் தமிழிலோ ஆங்கிலத்திலோ பேசலாம்.')}</p></li><li><h3>${tr('Know the plan before you pay','கட்டணம் செலுத்தும் முன் விவரங்களை அறியலாம்')}</h3><p>${tr('The office reviews your request and confirms the consultation details and fee before payment.','உங்கள் கோரிக்கையைப் பார்த்து, வழக்கறிஞர், சந்திப்பு நேரம், கட்டணம் ஆகிய விவரங்களை அலுவலகம் உறுதிசெய்யும்.')}</p></li><li><h3>${tr('Leave with a next step','அடுத்து என்ன செய்யலாம் என்பதைப் பார்க்கலாம்')}</h3><p>${tr('Keep the agreed actions, documents and consultation summary together in your client account.','ஆலோசனைக்குப் பிறகு செய்ய வேண்டியவை, ஆவணங்கள், ஆலோசனைக் குறிப்புகள் அனைத்தையும் உங்கள் கணக்கில் பார்க்கலாம்.')}</p></li></ol><p class="meeting-note">${tr('Proposed consultation flow · Subject to the firm’s approval.','இது முன்மொழியப்படும் நடைமுறை. நிறுவனம் ஒப்புதல் அளிக்க வேண்டும்.')}</p></section>
<section class="reading-room"><div class="reading-heading"><h2>${tr('Before you<br>sign anything.','கையெழுத்திடுவதற்கு<br>முன்…')}</h2><p>${tr('A few useful questions can make the first conversation easier.','கேட்க விரும்பும் கேள்விகளை முன்கூட்டியே தயாரித்தால், ஆலோசனை இன்னும் பயனுள்ளதாக இருக்கும்.')}</p></div><div class="reading-feature"><span>${tr('Property · Preparation guide','வீடு வாங்கும்போது')}</span><h3>${tr('Buying a home in Chennai? Start with what you have.','சென்னையில் வீடு வாங்குகிறீர்களா?')}</h3><p>${tr('The papers already available. The dates that matter. The questions you have not yet asked.','உங்களிடம் என்ன ஆவணங்கள் உள்ளன? முன்பணம் செலுத்த தேதி முடிவு செய்துள்ளீர்களா? எது பற்றிச் சந்தேகம் உள்ளது? இவற்றைச் சேர்த்துப் பார்க்கலாம்.')}</p>${button(tr('Read the guide','படித்துப் பார்க்கலாம்'),'service-guide','property',true)}</div><div class="reading-links">${link(tr('Before signing a rental agreement →','வாடகை ஒப்பந்தம் செய்ய உள்ளீர்களா? →'),'service-guide','rental')}${link(tr('A contract for your business →','தொழில் ஒப்பந்தம் தொடர்பான தகவல்கள் →'),'service-guide','business')}${link(tr('Browse all resources →','மேலும் அறியலாம் →'),'public','guides')}</div></section>
<section class="pocket-section"><div class="pocket-copy"><h2>${tr('The conversation<br>doesn’t end at the office.','ஆலோசனைக்குப் பிறகும்<br>தொடர்பில் இருக்கலாம்.')}</h2><p>${tr('See the next step without having to ask for the same update again.','அடுத்த படி என்ன என்பதை அறிய ஒவ்வொரு முறையும் அழைக்க வேண்டியதில்லை. உங்கள் கணக்கிலேயே தகவல்களைப் பார்க்கலாம்.')}</p><ul><li>${tr('Your appointments and preparation','சந்திப்பு நேரமும் அதற்கான தயாரிப்பும்')}</li><li>${tr('Documents requested by your lawyer','வழக்கறிஞர் கேட்ட ஆவணங்கள்')}</li><li>${tr('Reports and agreed next actions','ஆலோசனைக் குறிப்புகளும் அடுத்த வேலையும்')}</li></ul>${button(tr('See the client app','செயலியைப் பார்க்கலாம்'),'login','client:mobile',true)}</div><div class="pocket-preview"><div class="preview-top">${tr('CLIENT APP · ILLUSTRATION','செயலி எப்படி இருக்கும் · மாதிரி')}</div><p>${tr('Your next appointment','உங்கள் அடுத்த சந்திப்பு')}</p><h3>${tr('Property consultation','வீடு வாங்குவது பற்றி ஆலோசனை')}</h3><div class="appointment-date"><b>06</b><span>${tr('October · 10:00 AM','அக்டோபர் · காலை 10 மணி')}<br>${tr('At the office · Tamil','அலுவலகத்தில் · தமிழில்')}</span></div><div class="preview-update">${icon('file')}<div><b>${tr('One thing to prepare','தயாராக வைத்திருக்க வேண்டியது')}</b><p>${tr('Bring the property papers you already have.','உங்களிடம் உள்ள சொத்து ஆவணங்களை எடுத்து வாருங்கள்.')}</p></div></div><p class="preview-disclaimer">${tr('Illustrative appointment, not a real booking. App reminders are a proposed feature.','இது மாதிரி சந்திப்பு மட்டுமே. செயலியில் நினைவூட்டல் வசதியும் சேர்க்கலாம்.')}</p></div></section>
<section class="business-invitation"><h2>${tr('For the work<br>that keeps coming.','உங்கள் தொழிலுக்குத்<br>தொடர்ந்து உதவி தேவையா?')}</h2><div><p>${tr('Supplier agreements today. Employment documents next month. Explore an ongoing relationship with the firm, with scope and fees agreed upfront.','சப்ளையர் ஒப்பந்தங்கள், வேலை ஒப்பந்தங்கள் என அடிக்கடி உதவி தேவைப்படுகிறதா? எந்த உதவி கிடைக்கும், கட்டணம் என்ன என்பதை முதலில் ஒப்புக்கொள்ளலாம்.')}</p>${button(tr('Explore business support','தொழிலுக்கான உதவியைப் பார்க்கலாம்'),'public','services',true)}</div></section>
<section class="firm-invitation"><h2>${tr('Get to know the firm.','எங்களைப் பற்றி அறிந்துகொள்ளலாம்.')}</h2><p>${tr('Explore the places for verified reviews, recognition and client stories. Firm details will be added after confirmation.','வாடிக்கையாளர் அனுபவங்கள், மதிப்புரைகள், நிறுவன விவரங்கள் — உறுதிசெய்த பிறகு இங்கே சேர்ப்போம்.')}</p><div class="row">${link(tr('Reviews & recognition →','மதிப்புரைகள் & அங்கீகாரம் →'),'public','trust')}${link(tr('Story examples →','சில உதாரணங்கள் →'),'public','stories')}</div></section>
<section class="quiet-close"><h2>${tr('Start with what’s <br>on your mind.','உங்கள் சந்தேகத்தைப் பகிருங்கள்.<br>அதிலிருந்து தொடங்கலாம்.')}</h2><div class="row">${button(tr('Book a consultation','ஆலோசனைக்கு நேரம் தேர்ந்தெடுக்கவும்'),'start','direct')}${button(tr('Ask a question','ஒரு கேள்வி கேளுங்கள்'),'public','chat',true)}</div></section>`};
// The approved compact homepage is exclusive to narrow screens.
const compactPublicHome = publicHome;
const compactHomeViewport = window.matchMedia('(max-width:700px)');
publicHome = function () {
  return compactHomeViewport.matches ? compactPublicHome() : fullDesktopHome();
};
compactHomeViewport.addEventListener('change', () => {
  if (role === 'public' && page === 'home') render();
});
render();

