'use strict';
// Retain the full desktop composition before defining the compact homepage.
const fullDesktopHome = publicHome;
// Independent design review applied: a compact index, not repeated marketing blocks.
publicHome=function(){return `<section class="index-hero"><div><p class="place-note">${tr('Tamil & English · In person or online','தமிழ் & English · நேரில் அல்லது Online')}</p><h1>${tr('What would you like<br>to move forward?','என்ன உதவி<br>தேவைப்படுகிறது?')}</h1><p class="lead">${tr('A home. Your business. An agreement that matters. Start with what’s on your mind.','வீடு வாங்குகிறீர்களா? தொழிலுக்கு உதவி தேவையா? ஒரு ஒப்பந்தத்தை ஆய்வு செய்ய வேண்டுமா? இங்கிருந்து தொடங்கலாம்.')}</p><div class="row hero-actions">${button(tr('Book a consultation','ஆலோசனைக்கு நேரம் கேளுங்கள்'),'start','direct')}${button(tr('Ask a question','ஒரு கேள்வி கேளுங்கள்'),'public','chat',true)}</div></div><figure><img src="assets/justice.png" alt="${tr('Brass scales beside a legal book','சட்ட நூலுடன் தராசு')}" /></figure></section><section class="service-index" aria-label="${tr('Find your starting point','எங்கிருந்து தொடங்கலாம்')}"><div class="index-caption"><span>${tr('A place to begin','இங்கிருந்து தொடங்கலாம்')}</span>${link(tr('All services →','எல்லா சேவைகளும் →'),'public','services')}</div>${[
['property',tr('Buying a property','வீடு அல்லது சொத்து வாங்க'),tr('Bring the documents you have and the questions you want answered.','உங்களிடம் உள்ள ஆவணங்களையும் கேட்க வேண்டிய கேள்விகளையும் தயாராக வைத்துக்கொள்ளுங்கள்.')],
['rental',tr('A rental agreement','வாடகை ஒப்பந்தம்'),tr('Understand the agreement before signing, or discuss a rental concern.','கையெழுத்திடும் முன் ஒப்பந்தத்தைப் புரிந்துகொள்ளலாம்; வாடகை தொடர்பான சந்தேகங்களையும் பேசலாம்.')],
['business',tr('My business','என் தொழில்'),tr('Review a contract or discuss support for the work that keeps coming.','ஒப்பந்தத்தை ஆய்வு செய்யலாம்; தொடர்ந்து தேவைப்படும் உதவி பற்றியும் பேசலாம்.')],
['other',tr('Not sure where to start','எங்கிருந்து தொடங்குவது என்று தெரியவில்லையா?'),tr('Tell us what is on your mind. We will help you explore the right consultation.','என்ன சந்தேகம் என்று சொல்லுங்கள். எந்த ஆலோசனை பொருந்தும் என்று பார்க்கலாம்.')]
].map(([id,h,p],i)=>`<details name="service-index"><summary><span class="index-number">0${i+1}</span><span>${h}</span><span class="index-plus" aria-hidden="true">+</span></summary><div class="index-answer"><p>${p}</p><div class="row">${id==='other'?button(tr('Find my starting point →','எங்கிருந்து தொடங்கலாம் →'),'public','chat',true):`${button(tr('Book this review','இந்த ஆய்வுக்கு நேரம் கேளுங்கள்'),'service',id)}${button(tr('Ask about this','இதைப் பற்றிக் கேட்க'),'help-topic',id,true)}`}</div>${id!=='other'?link(tr('Read the preparation guide →','தயாரிப்புப் பட்டியலைப் பார்க்க →'),'service-guide',id):''}</div></details>`).join('')}</section><section class="client-note"><div><p class="place-note">${tr('After your first conversation','முதல் ஆலோசனைக்குப் பிறகு')}</p><h2>${tr('Your next steps.<br>In one place.','அடுத்த படிகள்.<br>ஒரே இடத்தில்.')}</h2></div><div><p>${tr('Appointments, requested documents and updates from your lawyer—on the website and in the proposed app.','சந்திப்புகள், கேட்கப்பட்ட ஆவணங்கள், வழக்கறிஞரின் தகவல்கள் — இணையதளத்திலும் முன்மொழியப்படும் செயலியிலும்.')}</p><div class="row">${button(tr('Explore the client experience →','Client அனுபவத்தைப் பார்க்க →'),'public','experience',true)}${link(tr('Client sign in →','Client Login →'),'login','client:web')}</div></div></section>`};
const editorialHeader=publicHeader,editorialFooter=footer;
publicHeader=function(){let h=editorialHeader();h=h.replace('<nav ',`<button class="mobile-menu-toggle" aria-expanded="false" aria-controls="public-menu" data-action="toggle-public-menu">${tr('Menu','Menu')} +</button><nav id="public-menu" `);return h};
footer=function(){return editorialFooter().replace('class="site-footer"','class="site-footer editorial-footer"')};
document.addEventListener('click',e=>{const b=e.target.closest('[data-action="toggle-public-menu"]');if(!b)return;e.preventDefault();const expanded=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!expanded));document.querySelector('.public-header')?.classList.toggle('menu-open',!expanded);});
render();
