'use strict';
// Navigation patch only: keep the approved public visual design and six workspaces.
let requestReceipt=false;
const navOldHeader=publicHeader,navOldRender=render,navOldMove=move;
publicHeader=function(){let h=navOldHeader();h=h.replace(/<button[^>]*data-action="public"[^>]*data-value="experience"[^>]*>[\s\S]*?<\/button>/,'');h=h.replace('class="signin"','class="nav-signin"');return h.replace('</nav>',`${button(tr('Book a consultation →','ஆலோசனைக்கு நேரம் கேளுங்கள் →'),'start','direct')}</nav>`)};
move=function(where){if(where==='mobile'&&role==='public'){requestReceipt=true;setRoute('public','web','booking')}else navOldMove(where)};
render=function(){navOldRender();if(role==='public'&&page==='booking'){const main=document.querySelector('main');main.querySelector('[data-action="login"][data-value="client:web"]')?.parentElement.remove();if(requestReceipt&&state.booking){main.innerHTML=`<section class="navigation-receipt">${eyebrow(tr('Request received','உங்கள் கோரிக்கை பெறப்பட்டது'))}<h1>${tr('Your next step is clear.','அடுத்த படி தெளிவாக இருக்கிறது.')}</h1>${statusPill(state.booking.status)}${summary(state.booking)}<p>${tr('The office reviews your request and confirms the details before payment. You can follow its progress in your client workspace.','அலுவலகம் கோரிக்கையைப் பார்த்து, கட்டணத்திற்கு முன் விவரங்களை உறுதிசெய்யும். அதன் நிலையை உங்கள் Client பக்கத்தில் பார்க்கலாம்.')}</p>${button(tr('Open my client workspace →','என் Client பக்கத்தைத் திற →'),'receipt-client')}</section>`}else if(state.booking&&!['cancelled','completed'].includes(state.booking.status)){main.insertAdjacentHTML('beforeend',button(tr('Open my client workspace →','என் Client பக்கத்தைத் திற →'),'receipt-client'))}}};
document.addEventListener('click',e=>{if(e.target.closest('[data-action="receipt-client"]')){requestReceipt=false;setRoute('client','web','consultations')}if(e.target.closest('[data-action="reset-confirm"]'))requestReceipt=false;},true);
render();
