'use strict';
// Clear, approachable professional Tamil; public copy written by intent.
const PUBLIC_TAMIL_COPY={
  "Our services": "எங்கள் சேவைகள்",
  "Resources": "பயனுள்ள தகவல்கள்",
  "Ask a question": "ஒரு கேள்வி கேளுங்கள்",
  "Ask a question →": "ஒரு கேள்வி கேளுங்கள் →",
  "Book a consultation": "ஆலோசனைக்கு நேரம் தேர்ந்தெடுக்கவும்",
  "Book a consultation →": "ஆலோசனைக்கு நேரம் தேர்ந்தெடுக்கவும் →",
  "Client sign in ↗": "உங்கள் கணக்கில் நுழைய →",
  "Client sign in →": "உங்கள் கணக்கில் நுழைய →",
  "For our clients": "வாடிக்கையாளர்களுக்கான வசதிகள்",
  "Buying a property": "வீடு அல்லது நிலம் வாங்குகிறீர்களா?",
  "A rental agreement": "வாடகை ஒப்பந்தம் தொடர்பான உதவி",
  "My business": "உங்கள் தொழிலுக்கான உதவி",
  "Not sure where to start": "எங்கிருந்து தொடங்குவது என்று தெரியவில்லையா?",
  "Bring the documents you have and the questions you want answered.": "எல்லா ஆவணங்களும் இப்போதே தேவையில்லை. உங்களிடம் உள்ள ஆவணங்களையும் உங்கள் சந்தேகங்களையும் வைத்து உரையாடலைத் தொடங்கலாம்.",
  "Understand the agreement before signing, or discuss a rental concern.": "வாடகை ஒப்பந்தத்தில் உள்ள விவரங்களைப் புரிந்துகொள்ளலாம். ஏற்கெனவே உள்ள வாடகைப் பிரச்சனைகள் குறித்தும் பேசலாம்.",
  "Review a contract or discuss support for the work that keeps coming.": "ஒரு ஒப்பந்தத்தை ஆய்வு செய்ய வேண்டுமா? அல்லது தொடர்ந்து சட்ட உதவி தேவையா? உங்கள் தேவைக்கு ஏற்ற உதவியைப் பற்றிப் பேசலாம்.",
  "Tell us what is on your mind. We will help you explore the right consultation.": "உங்கள் சூழ்நிலையை உங்கள் சொற்களில் பகிருங்கள். எந்த ஆலோசனை பொருந்தும் என்பதைச் சேர்ந்து பார்க்கலாம்.",
  "Book this review": "இந்த ஆய்வுக்கு நேரம் தேர்ந்தெடுக்கவும்",
  "Ask about this": "இது பற்றிக் கேளுங்கள்",
  "Read the preparation guide →": "என்ன தயாராக வைத்திருக்க வேண்டும்? →",
  "All services →": "அனைத்துச் சேவைகளும் →",
  "The right help.<br>For the work ahead.": "உங்கள் தேவைக்கு ஏற்ற<br>சட்ட உதவி.",
  "An important document, a business decision or support you need regularly. Start with your situation—we can help you find the right conversation.": "சொத்து ஆவணங்கள், தொழில் ஒப்பந்தங்கள் அல்லது தொடர்ந்து தேவைப்படும் சட்ட உதவி — உங்கள் தேவையைச் சொல்லுங்கள். அதற்கு ஏற்ற ஆலோசனையைப் பார்க்கலாம்.",
  "For the decisions that feel personal.": "உங்களுக்கு முக்கியமான முடிவுகளுக்கு.",
  "A legal partner for the way you work.": "உங்கள் தொழிலுக்குத் தேவையான சட்ட ஆதரவு.",
  "Useful answers.<br>In everyday language.": "எளிதில் புரிந்துகொள்ளும்<br>பயனுள்ள தகவல்கள்.",
  "Start with a short guide, explore official information or ask us where to begin.": "உங்கள் சூழ்நிலைக்கு ஏற்ற தகவல்களைப் படிக்கலாம். அரசு ஆதாரங்களைப் பார்க்கலாம். மேலும் சந்தேகம் இருந்தால் எங்களிடம் கேட்கலாம்.",
  "A good place to start.": "இங்கிருந்து தொடங்கலாம்.",
  "A conversation<br>with a next step.": "உங்கள் சந்தேகத்தைப்<br>பகிருங்கள்.",
  "Understand which consultation fits, then book when you are ready. You can always choose direct booking.": "உங்கள் தேவைக்கு எந்த ஆலோசனை பொருந்தும் என்பதை முதலில் பார்க்கலாம். நேரடியாக வழக்கறிஞரிடம் பேச விரும்பினால், ஆலோசனைக்கு நேரம் தேர்ந்தெடுக்கலாம்.",
  "Start with your situation.": "உங்கள் சூழ்நிலையைச் சொல்லுங்கள்.",
  "Understand the suggested next step.": "அடுத்து என்ன செய்யலாம் என்பதைப் பார்க்கலாம்.",
  "Choose whether to share the summary when booking.": "ஆலோசனைக்கு நேரம் கேட்கும்போது இந்த விவரங்களைப் பகிர விரும்புகிறீர்களா என்பதை நீங்களே முடிவு செய்யலாம்.",
  "What would you like help with?": "எது தொடர்பாக உதவி தேவை?",
  "Find a starting point →": "அடுத்த படியைப் பார்க்கலாம் →",
  "Go straight to booking →": "நேரடியாக ஆலோசனைக்கு நேரம் தேர்ந்தெடுக்கவும் →",
  "Welcome. What would you like help with? Choose an example to explore.": "வணக்கம்! எது தொடர்பாகப் பேச விரும்புகிறீர்கள்? கீழே உங்களுக்குப் பொருந்தும் தலைப்பைத் தேர்ந்தெடுக்கலாம்.",
  "For this example, the property is in Chennai. Which stage best describes your situation?": "இந்த உதாரணத்தில், நீங்கள் சென்னையில் சொத்து வாங்குவதாக எடுத்துக்கொள்வோம். தற்போது எந்த நிலையில் இருக்கிறீர்கள்?",
  "Researching a purchase": "வாங்குவது பற்றி யோசித்து வருகிறேன்",
  "Preparing to pay an advance": "முன்பணம் செலுத்தத் தயாராகிறேன்",
  "Already facing a problem": "ஏற்கெனவே ஒரு பிரச்சனை உள்ளது",
  "Before buying a flat in Chennai, prepare for the conversation.": "சென்னையில் வீடு வாங்குகிறீர்களா? ஆலோசனைக்கு முன் இவற்றைத் தயாராக வைத்திருக்கலாம்.",
  "A useful first conversation starts with your situation, the documents you already have and the questions you want answered. You do not need to know the legal terminology.": "என்ன வாங்கத் திட்டமிடுகிறீர்கள், உங்களிடம் என்ன ஆவணங்கள் உள்ளன, எது பற்றிச் சந்தேகம் உள்ளது என்பதைப் பகிருங்கள். சட்டச் சொற்களை அறிந்திருக்க வேண்டிய அவசியமில்லை.",
  "Bring context, not just paperwork.": "ஆவணங்களுடன் உங்கள் சூழ்நிலையையும் பகிருங்கள்.",
  "Explain what you are considering, what has already happened and whether a date has been agreed. The firm can then clarify the appropriate service and what else it needs.": "என்ன செய்யத் திட்டமிடுகிறீர்கள், இதுவரை என்ன நடந்துள்ளது, தேதி ஏதும் முடிவு செய்யப்பட்டுள்ளதா என்பதைச் சொல்லுங்கள். மேலும் என்ன தேவை என்பதை வழக்கறிஞர் விளக்குவார்.",
  "Can I start without every document?": "எல்லா ஆவணங்களும் இல்லாவிட்டாலும் பேசலாமா?",
  "Can I speak in Tamil?": "தமிழில் பேசலாமா?",
  "Does the checklist replace a legal review?": "இந்தப் பட்டியல் மட்டும் போதுமா?",
  "Your preparation, your pace.": "உங்களுக்கு வசதியான நேரத்தில் தயாராகலாம்.",
  "Use this checklist for the topic you are reading. Save it now, ask a question or book when you are ready.": "இந்தப் பட்டியலைச் சேமித்து வைத்துக்கொள்ளலாம். சந்தேகம் இருந்தால் கேளுங்கள். நீங்கள் தயாரானதும் ஆலோசனைக்கு நேரம் தேர்ந்தெடுக்கலாம்.",
  "Save this checklist ↓": "பட்டியலைச் சேமிக்கவும் ↓",
  "Ask about this topic →": "இது பற்றிக் கேளுங்கள் →",
  "Let’s find the right consultation.": "ஆலோசனைக்கு ஏற்ற நேரத்தைத் தேர்ந்தெடுக்கலாம்.",
  "What would you like to discuss?": "எது தொடர்பாகப் பேச விரும்புகிறீர்கள்?",
  "How would you like to meet?": "எந்த முறையில் பேச வசதியாக இருக்கும்?",
  "What happens after your request?": "நேரம் கேட்ட பிறகு என்ன நடக்கும்?",
  "Your next step is clear.": "உங்கள் கோரிக்கை பெறப்பட்டது.",
  "The office reviews your request and confirms the details before payment. You can follow its progress in your client workspace.": "அலுவலகம் உங்கள் கோரிக்கையைப் பார்த்து விவரங்களை உறுதிசெய்யும். அதன் பிறகு கட்டணம் செலுத்தலாம். கோரிக்கையின் நிலையை உங்கள் கணக்கில் பார்க்கலாம்.",
  "Open my client workspace →": "என் கணக்கில் பார்க்க →",
  "Start again": "மீண்டும் தொடங்கவும்",
  "Request consultation →": "ஆலோசனைக்கு நேரம் தேர்ந்தெடுக்கவும் →",
  "Read first": "முதலில் படித்துப் பார்க்கலாம்",
  "Ask the office to help choose": "அலுவலகத்தின் உதவியைக் கேட்கலாம்",
  "Clear advice. A considered next step.": "தெளிவான ஆலோசனை. நிதானமான அடுத்த படி.",
  "Your firm, wherever you are.": "நீங்கள் எங்கிருந்தாலும் தொடர்பில் இருக்கலாம்.",
  "Explore": "மேலும் பார்க்க",
  "PRIVATE CONCEPT · Sample content": "செயல்விளக்கத்திற்கான மாதிரி",
  "Choose demo journey": "மற்ற அனுபவங்களைப் பார்க்க",
  "Property document review": "சொத்து ஆவண ஆய்வு",
  "Rental agreement review": "வாடகை ஒப்பந்த ஆய்வு",
  "Business contract review": "தொழில் ஒப்பந்த ஆய்வு"
};
