'use strict';
const previousExperience=experienceBlock,previousServices=expandedServices,previousGuide=guide,previousLawyer=lawyerPage;
experienceBlock=function(){return previousExperience()+`<section class="public-section app-benefits">${eyebrow(tr('Your next step, wherever you are','எங்கிருந்தாலும் அடுத்த படி உங்கள் கையில்'))}<h2>${tr('Less chasing. More peace of mind.','தகவலுக்காக அலைய வேண்டாம்.')}</h2><div class="engagement-grid">${[
[tr('Remember your appointment','சந்திப்பை மறக்காமல் இருக்க'),tr('A proposed reminder brings the time, meeting format and preparation list together.','நேரம், சந்திக்கும் முறை, தயாரிப்புப் பட்டியல் — எல்லாம் ஒரே நினைவூட்டலில்.')],
[tr('Know what to send','எந்த ஆவணம் தேவை என்று தெரிந்துகொள்ள'),tr('See document requests and keep the files for your consultation in one place.','கேட்கப்பட்ட ஆவணங்களையும் ஆலோசனைக்கான கோப்புகளையும் ஒரே இடத்தில் பார்க்கலாம்.')],
[tr('See what happens next','அடுத்து என்ன நடக்கிறது என்று பார்க்க'),tr('Follow confirmation, document review and the summary shared after your consultation.','சந்திப்பு உறுதி, ஆவண ஆய்வு, ஆலோசனைக்குப் பின் பகிரப்படும் சுருக்கம் ஆகியவற்றைப் பார்க்கலாம்.')]
].map(([h,p])=>`<article><h3>${h}</h3><p>${p}</p></article>`).join('')}</div><p class="tiny">${tr('Proposed app experience. Reminders and notifications are illustrative, not connected.','செயலி முன்மொழிவு. நினைவூட்டல்கள் மாதிரிகள் மட்டுமே; இப்போது அனுப்பப்படாது.')}</p>${button(tr('Explore the client app →','Client செயலியைப் பார்க்க →'),'login','client:mobile',true)}</section>`};
expandedServices=function(){return previousServices().replace('<section id="firm-evidence"',`<section class="public-section business-example">${eyebrow(tr('Ongoing support · Example','தொடர்ந்த உதவி · உதாரணம்'))}<h2>${tr('A legal desk for your growing business.','வளரும் தொழிலுக்குத் தொடர்ந்து சட்ட உதவி.')}</h2><p class="lead">${tr('A small business needs a supplier agreement reviewed today, employment documents next month and a place to keep the agreed actions.','இன்று சப்ளையர் ஒப்பந்த ஆய்வு, அடுத்த மாதம் வேலை ஒப்பந்தங்கள், ஒப்புக்கொண்ட பணிகளைக் கண்காணிக்க ஒரு இடம்.')}</p><ol class="working-steps"><li>${tr('Discuss recurring needs','அடிக்கடி தேவைப்படும் உதவியைப் பேசுங்கள்')}</li><li>${tr('Agree scope, fees and response times','வேலை, கட்டணம், பதில் நேரத்தை ஒப்புக்கொள்ளுங்கள்')}</li><li>${tr('Share documents with the assigned lawyer','ஒதுக்கப்பட்ட வழக்கறிஞரிடம் ஆவணங்களைப் பகிருங்கள்')}</li><li>${tr('Track reviews and next actions in your Client workspace','Client பக்கத்தில் ஆய்வையும் அடுத்த பணிகளையும் பாருங்கள்')}</li></ol><p>${tr('One Client account for individual and business work. Each support arrangement is agreed with the firm.','தனிப்பட்ட மற்றும் தொழில் பணிகளுக்கு ஒரே Client கணக்கு. உதவியின் விவரங்களை நிறுவனத்துடன் ஒப்புக்கொள்ளலாம்.')}</p>${button(tr('Discuss ongoing support →','தொடர்ந்த உதவி பற்றிப் பேசலாம் →'),'business-enquiry','',true)}</section><section id="firm-evidence"`)};
guide=function(){return previousGuide().replace(/<aside[\s\S]*?<\/aside>/,'')+`<section class="public-section preparation-next"><h2>${tr('Your preparation, your pace.','உங்கள் நேரத்தில் தயாராகுங்கள்.')}</h2><p>${tr('Use this checklist for the topic you are reading. Save it now, ask a question or book when you are ready.','நீங்கள் படிக்கும் தலைப்புக்கான பட்டியலைச் சேமிக்கலாம். சந்தேகம் கேட்கலாம், தயாரானதும் நேரம் கேட்கலாம்.')}</p><div class="row">${button(tr('Save this checklist ↓','இந்தப் பட்டியலைச் சேமி ↓'),'guide-download','',true)}${button(tr('Ask about this topic →','இதைப் பற்றிக் கேட்க →'),'help-topic',state.service,true)}${button(tr('Book a consultation','ஆலோசனைக்கு நேரம் கேளுங்கள்'),'service',state.service)}</div></section>`};
lawyerPage=function(){if(!['schedule','matters','followups'].includes(page))return previousLawyer();const b=state.booking;const assigned=b?.assigned==='A'&&b.status!=='cancelled';if(!assigned)return previousLawyer();
if(page==='schedule')return heading(tr('Your consultation schedule.','உங்கள் ஆலோசனை அட்டவணை.'),tr('Appointment time, meeting format and preparation at a glance.','சந்திப்பு நேரம், சந்திக்கும் முறை, தயாரிப்பு — ஒரே பார்வையில்.'))+`<section class="report-paper"><p class="eyebrow">${slotName(b.slot)} · ${tr('India time · Sample','இந்திய நேரம் · மாதிரி')}</p><h2>${serviceName(b.service)}</h2>${statusPill(b.status)}<p>${formatName(b.format)} · ${b.language==='ta'?tr('Tamil','தமிழ்'):tr('English','ஆங்கிலம்')}</p><p>${tr('Demo visitor ·','மாதிரி வருகையாளர் ·')} ${b.id}</p><p>${b.status==='awaiting_payment'?tr('Awaiting client confirmation. This appointment is not yet confirmed.','வாடிக்கையாளர் உறுதிப்படுத்தல் நிலுவை. சந்திப்பு இன்னும் உறுதியாகவில்லை.'):b.status==='completed'?tr('Recorded as completed. Continue with the consultation summary.','முடிந்ததாகப் பதிவானது. ஆலோசனைச் சுருக்கத்தைப் பகிரலாம்.'):tr('Prepare the available documents before the meeting.','சந்திப்புக்கு முன் கிடைக்கும் ஆவணங்களைப் பாருங்கள்.')}</p>${button(tr('Open the matter →','பணியைத் திற →'),'page','matters',true)}</section>`;
if(page==='matters')return heading(tr('Your assigned matters.','உங்களுக்கு ஒதுக்கப்பட்ட பணிகள்.'),tr('The client context, documents and progress of each matter.','வாடிக்கையாளர் விவரம், ஆவணங்கள், பணியின் முன்னேற்றம்.'))+`<section class="report-paper"><p>${b.id} · ${tr('Demo visitor','மாதிரி வருகையாளர்')}</p><h2>${serviceName(b.service)}</h2>${statusPill(b.status)}${b.summary?`<p>${stageName(b.summary)}</p>`:''}<div class="working-steps"><div><h3>${tr('Documents','ஆவணங்கள்')}</h3><p>${extra.uploaded?(extra.reviewed?tr('Sample document reviewed','மாதிரி ஆவணம் ஆய்வு செய்யப்பட்டது'):tr('One sample awaiting review','ஒரு மாதிரி ஆய்விற்காகக் காத்திருக்கிறது')):tr('No sample added yet','இன்னும் மாதிரி சேர்க்கப்படவில்லை')}</p>${link(tr('Open documents →','ஆவணங்களைத் திற →'),'page','documents')}</div><div><h3>${tr('Consultation','ஆலோசனை')}</h3><p>${slotName(b.slot)}</p>${link(tr('View schedule →','அட்டவணையைப் பார்க்க →'),'page','schedule')}</div><div><h3>${tr('Client update','வாடிக்கையாளர் தகவல்')}</h3><p>${extra.report?tr('Summary shared','சுருக்கம் பகிரப்பட்டது'):tr('Summary not shared yet','சுருக்கம் இன்னும் பகிரப்படவில்லை')}</p>${link(tr('Open follow-ups →','தொடர் பணிகளைத் திற →'),'page','followups')}</div></div>${b.status==='confirmed'?button(tr('Mark consultation completed','ஆலோசனை முடிந்ததாகக் குறி'),'attend'):''}</section>`;
return heading(tr('Follow-ups that need your attention.','உங்கள் கவனம் தேவைப்படும் தொடர் பணிகள்.'),tr('Keep pending actions separate from your appointment calendar.','சந்திப்பு அட்டவணையிலிருந்து நிலுவைப் பணிகளைத் தனியாகப் பாருங்கள்.'))+`<section class="task-row"><div><h3>${tr('Document review','ஆவண ஆய்வு')}</h3><p>${extra.uploaded?(extra.reviewed?tr('Done · sample reviewed','முடிந்தது · மாதிரி ஆய்வு செய்யப்பட்டது'):tr('Pending · one sample needs review','நிலுவை · ஒரு மாதிரியை ஆய்வு செய்ய வேண்டும்')):tr('No documents awaiting review','ஆய்விற்காக ஆவணங்கள் இல்லை')}</p>${link(tr('Open review queue →','ஆய்வுப் பட்டியலைத் திற →'),'page','documents')}</div></section><section class="task-row"><div><h3>${tr('Share the consultation summary','ஆலோசனைச் சுருக்கத்தைப் பகிருங்கள்')}</h3><p>${extra.report?tr('Done · visible in the client’s Reports','முடிந்தது · Client அறிக்கைகளில் தெரியும்'):b.status==='completed'?tr('Ready · consultation completed','தயார் · ஆலோசனை முடிந்தது'):tr('Available after the consultation is completed','ஆலோசனை முடிந்த பிறகு பகிரலாம்')}</p>${b.status==='completed'&&!extra.report?button(tr('Share sample summary with client','மாதிரிச் சுருக்கத்தை வாடிக்கையாளருடன் பகிர்'),'publish-report'):link(tr('Open the matter →','பணியைத் திற →'),'page','matters')}</div></section>`;
};
document.addEventListener('click',e=>{if(!e.target.closest('[data-action="guide-download"]'))return;e.preventDefault();const text=serviceName(state.service)+'\n\n'+checklistText(state.service).map((s,i)=>`${i+1}. ${s}`).join('\n')+'\n\n'+tr('Preparation checklist. The firm confirms the review scope.','தயாரிப்புப் பட்டியல். ஆய்வின் விவரங்களை நிறுவனம் உறுதிசெய்யும்.');const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`preparation-${state.service}-${lang}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
render();
